Fix #23 error inflating in ChapterRenderer
pedrovgs/EffectiveAndroidUI pull request #28
Opened 2017-06-16 00:23 UTC by hugoangeles0810

The PR fixes the #23 issue.

The exception occurs when I've  tested the app in API level < 21, maybe by conflicts in style inheritance.

2017-06-16 06:43 UTC, pedrovgs requested changes
Hi @hugoangeles0810 thanks for your contribution. Could you review your code formatter configuration? You seem to be using the default one. Could you use the project checkstyle and reformat the code before merging this PR?

2017-06-28 10:53 UTC, pedrovgs approved these changes

2017-06-28 10:54 UTC, merged

2017-06-28 10:54 UTC, pedrovgs commented
Thanks for your contribution @hugoangeles0810 😃

2017-06-28 16:57 UTC, hugoangeles0810 commented
You are welcome @pedrovgs :grinning: